def Uncorrupt():
	global PinorINI
	Uncorruptor = configparser.ConfigParser(); Uncorruptor.read(PinorINI)
	Uncorruptor.set('Global', 'gamecorrupted', "False")
	Uncorruptor.set('Shop States', 'kiku', 'allowed')
	Uncorruptor.set('Shop States', 'tanpopo', 'allowed')
	Uncorruptor.set('Shop States', 'nodium', 'allowed')
	Uncorruptor.set('Shop States', 'ocean', 'allowed')
	Uncorruptor.set('Shop States', 'archlekia', 'allowed')
	Uncorruptor.set('Shop States', 'tanggal', 'allowed')
	Uncorruptor.set('Shop States', 'dyarix', 'allowed')
	Uncorruptor.set('Battle', 'Focused Player', 'Pinori')
	Uncorruptor.set('Battle', 'MaxHP', '10')
	Uncorruptor.set('Battle', 'HP', '10')
	Uncorruptor.set('Battle', 'Level', '1')
	Uncorruptor.set('Battle', 'atk', '2')
	Uncorruptor.set('Battle', 'DEF', '6')
	Uncorruptor.set('Battle', 'exp', '0')
	Uncorruptor.set('Battle', 'AkuronMaxHP', '70')
	Uncorruptor.set('Battle', 'AkuronHP', '70')
	Uncorruptor.set('Battle', 'AkuronLevel', '5')
	Uncorruptor.set('Battle', 'AkuronATK', '15')
	Uncorruptor.set('Battle', 'AkuronDEF', '10')
	Uncorruptor.set('Battle', 'akuronexp', '350')
	Uncorruptor.set('Battle', 'SanaMaxHP', '100')
	Uncorruptor.set('Battle', 'SanaHP', '100')
	Uncorruptor.set('Battle', 'SanaLevel', '7')
	Uncorruptor.set('Battle', 'SanaATK', '6')
	Uncorruptor.set('Battle', 'SanaDEF', '9')
	Uncorruptor.set('Battle', 'sanaexp', '700')
	Uncorruptor.set('Battle', 'YamiMaxHP', '120')
	Uncorruptor.set('Battle', 'YamiHP', '120')
	Uncorruptor.set('Battle', 'YamiLevel', '11')
	Uncorruptor.set('Battle', 'YamiATK', '25')
	Uncorruptor.set('Battle', 'YamiDEF', '5')
	Uncorruptor.set('Battle', 'yamiexp', '2000')
	Uncorruptor.set('Battle', 'MillieMaxHP', '0')
	Uncorruptor.set('Battle', 'MillieHP', '0')
	Uncorruptor.set('Battle', 'MillieLevel', '0')
	Uncorruptor.set('Battle', 'MillieATK', '-1')
	Uncorruptor.set('Battle', 'MillieDEF', '999999999999999999')
	Uncorruptor.set('Battle', 'millieexp', '0')
	Uncorruptor.set('Progress', 'Yami Defeated', 'False')
	Uncorruptor.set('Progress', 'Krystal Defeated', 'False')
	Uncorruptor.set('Progress', 'Shado Guards Defeated', 'False')
	Uncorruptor.set('Progress', 'Shado Archlekia Defeated', 'False')
	Uncorruptor.set('Progress', 'Location', 'Kiku Village')
	Uncorruptor.set('Progress', 'Steps Taken', '0')
	Uncorruptor.set('Progress', 'Kills', '0')
	Uncorruptor.set('Progress', 'Spares', '0')
	Uncorruptor.set('Progress', 'NPC Kills', '0')
	Uncorruptor.set('Progress', 'Route', 'Traditional')
	Uncorruptor.set('Progress', 'Kiku Village Population', '5')
	Uncorruptor.set('Progress', 'Tanpopo Town Population', '6')
	Uncorruptor.set('Progress', 'Nodium Valley Population', '11')
	Uncorruptor.set('Progress', 'Crystalline Oceanfront Population', '13')
	Uncorruptor.set('Progress', 'Archlekia Population', '13')
	Uncorruptor.set('Progress', 'Tanggal Volcano Population', '18')
	Uncorruptor.set('Progress', 'Dyarix Population', '25')
	Uncorruptor.set('Shadorako', 'hard', 'False')
	Uncorruptor.set('Shadorako', 'phase', '1')
	Uncorruptor.set('Shadorako', 'total deaths', '0')
	Uncorruptor.set('Shadorako', 'deaths', '0')
	Uncorruptor.set('Shadorako', 'max hp', '2000')
	Uncorruptor.set('Shadorako', 'hp', '2000')
	Uncorruptor.set('Shadorako', 'decoded', 'False')
	Uncorruptor.set('Shadorako', 'death by option 4', 'False')
	Uncorruptor.set('Shadorako', 'earth', '550')
	Uncorruptor.set('Shadorako', 'water', '250')
	Uncorruptor.set('Shadorako', 'fire', '750')
	Uncorruptor.set('Shadorako', 'magic', '1000')
	Uncorruptor.set('Shadorako\'s Lair', 'floor', '1')
	Uncorruptor.set('Shadorako\'s Lair', 'room', '1')
	Uncorruptor.set('Shadorako\'s Lair', 'steps', '0')
	Uncorruptor.set('Shadorako\'s Lair', 'bleed', '0')
	for character in ["Akuron", "Sana", "Yami"]:
		for charstuff in ["task", "state", "distance", "purchase", "meetup"]: Uncorruptor.set("Character Tasks", f"{character.lower()} {charstuff}", "None" if charstuff not in ["state", "distance"] else "present" if charstuff == "state" else "0")
	with open(PinorINI, "w") as Galaxette: Uncorruptor.write(Galaxette)
	EnemyINISetup()